version: "2"

volumes:
  spotifycache:
  pihole_config:
  dnsmasq_config:


services:

  emojifyer_backend:
    build: ./app/backend
    network_mode: host
    restart: on-failure
    ports:
      - 4356:4356

  telegram_bot:
    build: ./app/telegram
    network_mode: host
    restart: on-failure

  messenger_bot:
    build: ./app/messenger
    network_mode: host
    ports:
      - 80:80