version: "2"
 
services:
  emojifyer_backend:
    build: ./app/backend
      # context: ./app/backend
    # restart: on-failure
    ports:
      - 80:80
  telegram_bot:
    build: ./app/telegram
      # context: ./app/telegram
    # restart: on-failure

networks:
  default:
    driver: custom-network-1