version: "2"

services:
  emojifyer_backend:
    build: ./app/backend
    network_mode: host
    restart: on-failure
    # networks:
    #   - backend
    ports:
      - 4356:4356
  telegram_bot:
    build: ./app/telegram
    # networks:
    #   - backend
    #   - frontend
    network_mode: host
    restart: on-failure
  messenger_bot:
    build: ./app/messenger
    network_mode: host
    ports:
      - 80:80

# networks:
#   backend:
#     driver: bridge
#   frontend:
#     driver: host
